### ISSUE TITLE
Fix tokenization of  n't 

### ISSUE THREAD

**Issue by callison-burch** [kirubarajan/roft#12]
Replace all instances of " n't" with "n't".

**Comment by daphnei** [comment]
Assigning to Liam to fix this in our dataset files.

**Comment by daphnei** [comment]
@liamdugan you should go through a bunch of the text, and try to find as many of these as you can to fix. Another one that should be fixed is ` ’ ` should be `'`.

**Comment by daphnei** [comment]
Liam has updated the prompts, still need to regenerate continuations.

**Comment by daphnei** [comment]
Continuations have been regenerated!
