### ISSUE TITLE
Remove Splash Page

### ISSUE THREAD

**Issue by liamdugan** [kirubarajan/roft#142]
I think we should remove the splash page and make the `/` endpoint go directly to `/annotate` with the Random playlist. This would be more similar to how https://www.whichfaceisreal.com/ does it, they put you right into the action. We can still keep the splash page but put it in a new tab in the top-level menu named "About".

The top level menu would then look something like this:
<img width="597" alt="header" src="https://user-images.githubusercontent.com/14120375/114930021-88f7da80-9e02-11eb-808d-685348aecf96.png">

The mapping would be:
"Real or Fake Text" -> `/play`
"Play" -> `/play`
"About" -> `/splash`
"Help" -> `/onboard`
"Leaderboard" -> `/leaderboard`
"Save Progress" -> `/login`

We might also consider changing the "Play" button to say something like "Select Category" so that it's clearer that that is its main purpose.

Another consideration would be that, in the current form, this page wouldn't have a "Log in" button and so users that come to the page looking to log in would be confused. If we change "Save Progress" to say "Log in" then we lose that extra incentive for temp users to make an account. Maybe we say "Save Progress by Logging in" (?) Open to suggestions here

**Comment by kirubarajan** [comment]
I think this PR looks great! 

> Another consideration would be that, in the current form, this page wouldn't have a "Log in" button and so users that come to the page looking to log in would be confused. If we change "Save Progress" to say "Log in" then we lose that extra incentive for temp users to make an account. Maybe we say "Save Progress by Logging in" (?) Open to suggestions here

We can also just have a button for Save Progress and a button for Log In since they have different functionality anyway.

**Comment by liamdugan** [comment]
Don't they both go to the same endpoint? `/login` ?
