### ISSUE TITLE
If the same prompt is used to generate text multiple times, a user should only one of them

### ISSUE THREAD

**Issue by callison-burch** [kirubarajan/roft#15]
I saw multiple stories generated from this prompt:

> "I'm sorry Mr. Abraham, but we must; foreclose on your house" Clark struggles with a check and pen, out of his pocket "here, here please I'll make out my first mortgage, just cash it in two week's" the teller gets up and walks away, Clark sits in the leather couch, staring at the mahogany desk; for several minutes, until a guard stomps over and asks Clark to leave.

Users should only see a single story generated from the same prompt, since their judgements are then biased by what they know having revealed the answers from the previous one.

**Comment by callison-burch** [comment]
I also got this prompt twice:
> I still do n't know quite what to think about that week.

**Comment by daphnei** [comment]
Assigning to Arun to look into this.

**Comment by liamdugan** [comment]
#22 is related here, marking as fixed
