### ISSUE TITLE
Filter out examples where the prompt is either too short or too long.

### ISSUE THREAD

**Issue by daphnei** [kirubarajan/roft#22]

**Comment by daphnei** [comment]
How to fix this:
1. Add code to [populate.py(https://github.com/kirubarajan/roft/blob/master/annotation/populate.py) to avoid adding into database examples from json where the prompt is either too short or too long.

**Comment by liamdugan** [comment]
Fixed the error in the original colab notebook that caused this. Missed indent on the while loop makes us insert the prompt into the json every time, regardless of if it passes the length sum = 10 check.

Tangentially this also solves the duplicates issue, duplicates were just prompts that didn't get enough continuation but both the prompt that was too short and the future attempts to generate longer continuations are all added to the json.

I'll push changes for now to populate.py to avoid having to rerun generations
