### ISSUE TITLE
Copy on the play page

### ISSUE THREAD

**Issue by callison-burch** [kirubarajan/roft#25]
On the Play page https://roft.io/play/ I think that the copy is too technical.

> Generations from GPT-2 XL with prompts taken from the Reddit Writing Prompts dataset.

and 

> Generations from GROVER with prompts taken from the New York Times. 

Are too technical and jargon.

How about turning them into things that would make them seem fun?  

> Can a computer write a short story that makes sense?  
 
and 

> Donald Trump thinks the NYTimes fake news, can you spot when our computer wrote the article?

**Comment by liamdugan** [comment]
Related to #48 . Updated in commit 05d811134df05e5fc07c5e72c0fa20e550eac027 - waiting to PR until we're sure there's agreement on these descriptions
