### ISSUE TITLE
Remove NSFW prompts.

### ISSUE THREAD

**Issue by daphnei** [kirubarajan/roft#27]

**Comment by liamdugan** [comment]
Used the [profanityfilter](https://github.com/areebbeigh/profanityfilter) library for this with no word boundaries. 

[https://github.com/areebbeigh/profanityfilter/blob/master/profanityfilter/data/badwords.txt](https://github.com/areebbeigh/profanityfilter/blob/master/profanityfilter/data/badwords.txt) is the list of words if people want to check it out.
