### ISSUE TITLE
Filter out duplicate sentences in human prompts

### ISSUE THREAD

**Issue by liamdugan** [kirubarajan/roft#30]
Try to run a very barebones filtering step to remove when there are duplicate human written sentences (maybe do very high threshold word2vec average cosine similarity between sentences as a pre-processing step before generating?)

**Comment by liamdugan** [comment]
#22 is related to the same bug here. The sampling never gives duplicates however we accidentally add generations that do not meet the length threshold into the json multiple times with different continuations.

I also added a filtering step to the colab that checks first sentences of prompts for duplicates just in case we ever do end up sampling duplicate prompts (which may happen if we decide to ever run sample_corpus on the same file twice)

**Comment by daphnei** [comment]
Let's do this for future datasets (remove duplicates)

**Comment by liamdugan** [comment]
Added in pr #95
