### ISSUE TITLE
Navigating to roft.io when logged in takes you to the profile page

### ISSUE THREAD

**Issue by liamdugan** [kirubarajan/roft#32]
When I navigate to roft.io I get sent to roft.io/profile/liamdugan -- the log out button wasn't easily visible from there. 

We might want to change this behavior to either navigate a logged-in user to a version of the ROFT homepage that doesn't have the log in section or navigate them to the "play" page

**Comment by daphnei** [comment]
Fix:
1. Test out removing redirect [here](https://github.com/kirubarajan/roft/blob/master/annotation/core/views.py#L75)

**Comment by kirubarajan** [comment]
Implemented new functionality:
1. Logging in to an existing account will take you to the Play page.
2. Signing up a new account will take you to the Help/Onboarding page.
