### ISSUE TITLE
Add non-technical descriptions of datasets.

### ISSUE THREAD

**Issue by daphnei** [kirubarajan/roft#48]

**Comment by liamdugan** [comment]
Updated with descriptions listed by ccb in issue #25 in commit 05d811134df05e5fc07c5e72c0fa20e550eac027 
Will wait to merge until people generally agree that these are the descriptions we want to go with

**Comment by daphnei** [comment]
I just went a head and merged this. We still need to update populate.py to read in the new field and update the html to render it.
