### ISSUE TITLE
Add more bad-word filtering to the AMT worker username generation script.

### ISSUE THREAD

**Issue by daphnei** [kirubarajan/roft#65]
Just noticed one of the AMT workers was assigned the username: bitchy_mackerel

**Comment by liamdugan** [comment]
I actually manually took that username out and used it myself as a test account to make sure that turkers were given attention checks. No turker was ever assigned it thankfully. I'll definitely add in more filtering to make sure that doesn't happen again

**Comment by daphnei** [comment]
Awesome, thanks for checking this!
