### ISSUE TITLE
Add generation metadata to EvaluationText

### ISSUE THREAD

**Issue by liamdugan** [kirubarajan/roft#69]
Currently the EvaluationText model in the database only stores the prompt text, body text, and the boundary number.

We should have the following:
- the dataset the example was taken from (Reddit, NYT, fairytales)
- the model used to generate the continuation (GPT-2, GROVER, etc.)
- the hyperparameters of the model (p value, temperature, size (xl/large), etc.)
- the date of generation

These should be added to the generations.json by the colab notebook so that they can be incorporated into the EvaluationText models at database population time

**Comment by daphnei** [comment]
This issue is for adding the new fields to the database,

**Comment by daphnei** [comment]
Done.
