### ISSUE TITLE
Logic for "Number of correctly identified boundaries: " is wrong.

### ISSUE THREAD

**Issue by daphnei** [kirubarajan/roft#75]
For user "foo", it reads 0 but it should read at least 1. This user got the following one correct: 
https://roft.io/annotate/?group=1&qid=243

**Comment by daphnei** [comment]
Possible off-by-one error.

**Comment by liamdugan** [comment]
Bumping this one back to @daphnei since this was likely introduced during the changes made in this commit 74a08c9f3fd67dabb79a59f83555249d8efebd5c (should be in lines 70-72 of views.py)

**Comment by Sherry2001** [comment]
This should be fixed in PR #128

**Comment by liamdugan** [comment]
Yep, marking this one as fixed
