### ISSUE TITLE
Add help text to explain the metrics we show on the Profile page.

### ISSUE THREAD

**Issue by daphnei** [kirubarajan/roft#89]
For “Average distance from correct boundary,” mine is a positive number. I don’t know if a negative number is possible, but it is unclear what direction from the correct boundary this average distance is in.

**Comment by Sherry2001** [comment]
In most recent pull request changed it so "Avg distance from correct boundary" can be negative too. (Before it was absolute value). Left a note about negative meaning it was before correct boundary. Added an explanation box for how the points are calculated. The other metrics should be self explanatory.

**Comment by liamdugan** [comment]
Marking this as fixed
