### ISSUE TITLE
Add giant play button to home page.

### ISSUE THREAD

**Issue by daphnei** [kirubarajan/roft#90]
It might be helpful to have a big “Play Game” button at the bottom of the Roft.io homepage, which reveals the “Sign Up / Log In” section of the web page when it is clicked. When I first visited the website, at a glance it wasn't clear that there was an active game component right here on the website.

**Comment by liamdugan** [comment]
I actually think it probably would be better if we just took our users right into the game with Random playlist instead of showing them a large "Play Game" button.

**Comment by kirubarajan** [comment]
Agreed.

**Comment by liamdugan** [comment]
marked as obsolete
