### ISSUE TITLE
Improve UI for showing prompt and continuations

### ISSUE THREAD

**Issue by daphnei** [kirubarajan/roft#91]
(This might be just me, but) When you start a game, the first sentence under “Continuation of text” is already showing and has a box border. This attracts the eye straight to that box, skipping over the human written prompt, causing you to have to go back to read the prompt. It could be nice to show only the original text prompt in a color or border-emphasized way to attract eyes, and not show any continuation texts at first. When the player presses a “start round” or “start” button, then the first continuation text shows.

**Comment by liamdugan** [comment]
I think this was fixed by #94 so I'm closing it
