### ISSUE TITLE
Run GROVER for all p values on all datasets

### ISSUE THREAD

**Issue by liamdugan** [kirubarajan/roft#99]
We should attempt to run GROVER on all 4 datasets to show that certain models are worse at certain genres than others. The hypothesis here would be that GROVER would get a good trick score on NYT and a bad trick score on Reddit, Speeches, and wikihow. Hopefully we can find a way to optimize the running of GROVER - maybe google cloud will help us with that

**Comment by daphnei** [comment]
Not going to do.
